name: Deploy to Staging

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch: # Allows manual triggering

env:
  # Base path for all plugins - automatically appends repo name
  PLUGINS_BASE_PATH: '/public/wp-content/plugins'

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better git operations

      - name: Set plugin path
        id: plugin-path
        run: |
          # Automatically construct the plugin path from repo name
          PLUGIN_NAME="${{ github.event.repository.name }}"
          REMOTE_PATH="${{ env.PLUGINS_BASE_PATH }}/${PLUGIN_NAME}/"
          echo "remote_path=${REMOTE_PATH}" >> $GITHUB_OUTPUT
          echo "plugin_name=${PLUGIN_NAME}" >> $GITHUB_OUTPUT
          echo "📁 Deploying to: ${REMOTE_PATH}"

      - name: Deploy to Staging via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SIERRA_SFTP_HOST }}
          username: ${{ secrets.SIERRA_SFTP_USERNAME }}
          password: ${{ secrets.SIERRA_SFTP_PASSWORD }}
          port: ${{ secrets.SIERRA_SFTP_PORT }}
          protocol: ftps
          # Auto-constructed plugin path based on repository name
          server-dir: ${{ steps.plugin-path.outputs.remote_path }}

          # Exclude development files
          exclude: |
            **/.git*
            **/.git*/**
            **/.DS_Store
            **/.env*
            **/tests/**
            **/__tests__/**
            **/*.test.php
            **/*.spec.php
            .github/**
            .vscode/**

          log-level: verbose

      - name: Deployment Summary
        if: success()
        run: |
          echo "✅ Successfully deployed ${{ steps.plugin-path.outputs.plugin_name }} plugin to staging!"
          echo "📁 Remote path: ${{ steps.plugin-path.outputs.remote_path }}"
          echo "📦 Branch: ${{ github.ref_name }}"
          echo "🔨 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Deployment failed for ${{ steps.plugin-path.outputs.plugin_name }}!"
          echo "Please check the logs above for details."
